# -*- coding: utf-8 -*-
"""Main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gIpVsWFDBZVivcCzeOlRktMXibofRVYS
"""

!pip install shap numpy matplotlib scikit-learn

import shap
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC

data = load_breast_cancer()

X, y = data['data'], data['target']

data['target_names']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

clf = LinearSVC()
clf.fit(X_train, y_train)

clf.score(X_test, y_test)

explainer = shap.KernelExplainer(clf.predict, shap.kmeans(X_train, 10))

shap_values = explainer.shap_values(X_test)

shap.summary_plot(shap_values, X_test, feature_names=data['feature_names'])